server:
  port: 8080

spring:
  mvc:
    cors:
      allowed-origins: http://localhost:4200

  mail:
    host: smtp.gmail.com
    port: 587
    username: kat944166@gmail.com
    password: auffsjlmiczsejpl
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    connectiontimeout: 5000
    timeout: 3000
    writetimeout: 5000

  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbquiz?currentSchema=webschema

  jpa:
    properties:
      hibernate:
        format_sql: true
      hibernate.default_schema: webschema
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    user: postgres
    password: root
    default-schema: webschema
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbquiz?currentSchema=webschema

application:
  security:
    jwt:
      secret-key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      expiration: 86400000
      refresh-token:
        expiration: 604800000